#!/usr/bin/env python
import sys
import clientnode
import masternode
import signal
if __name__ == '__main__':

    port = None
    if len(sys.argv) < 3:
        print("Missing parameters")
        sys.exit(1)
    if len(sys.argv) == 4:
        port = sys.argv[3]

    module = sys.argv[1]
    command = sys.argv[2]
    if module == "masternode" and command == "start":

        if port is None:
            masternode.start()
        else:
            masternode.start(port)

    elif module == "clientnode" and command == "start":
        ip_address = sys.argv[3]
        port = sys.argv[4]
        if port is None:
            clientnode.start()
        else:
            clientnode.start(ip_address, port)
    else:
        print("Error parameters. See to documentation.")

